# Generated by Django 5.2.7 on 2025-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_players',
            field=models.ManyToManyField(related_name='fans', to='players.player'),
        ),
    ]
