# Generated by Django 5.2.7 on 2025-11-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(null=True)),
                ('jersey_number', models.IntegerField(null=True)),
                ('place_of_birth', models.CharField(max_length=250)),
                ('place_of_birth_title', models.CharField(max_length=250)),
                ('place_of_birth_float', models.URLField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('height', models.FloatField(null=True)),
                ('foot', models.FloatField(max_length=10, null=True)),
                ('citizenship', models.JSONField(null=True)),
                ('citizenship_flag', models.JSONField(null=True)),
                ('headshot', models.URLField(null=True)),
                ('club', models.CharField(max_length=250)),
                ('club_logo', models.URLField(max_length=250, null=True)),
                ('main_position', models.CharField(max_length=250, null=True)),
                ('other_positions', models.JSONField(null=True)),
                ('national_team', models.CharField(null=True)),
                ('national_team_flag', models.URLField(null=True)),
                ('caps', models.IntegerField(null=True)),
                ('international_goals', models.IntegerField(null=True)),
                ('market_value', models.IntegerField(null=True)),
                ('league_name', models.CharField(max_length=250, null=True)),
                ('league_level', models.CharField(max_length=250, null=True)),
                ('league_logo', models.URLField(max_length=250, null=True)),
                ('joined_date', models.DateField(null=True)),
                ('contract_expires', models.DateField(null=True)),
                ('agency_info', models.JSONField(null=True)),
                ('club_stats', models.JSONField(null=True)),
                ('national_team_stats', models.JSONField(null=True)),
                ('current_season_stats', models.JSONField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id', 'market_value'], name='players_pla_id_7bc858_idx')],
            },
        ),
    ]
