# Generated by Django 5.2.7 on 2025-11-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='place_of_birth_float',
            new_name='place_of_birth_flag',
        ),
    ]
