# Generated by Django 5.2.7 on 2025-11-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_rename_place_of_birth_float_player_place_of_birth_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='foot',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
