# Generated by Django 5.2.7 on 2025-11-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_foot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='place_of_birth_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
