# Generated by Django 5.2.7 on 2025-11-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': [models.OrderBy(models.F('market_value'), descending=True, nulls_last=True), models.OrderBy(models.F('caps'), descending=True, nulls_last=True)]},
        ),
    ]
